name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build all APKs
      run: ./gradlew assembleRelease

    - name: Upload all APKs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: All-APKs
        path: app/build/outputs/apk/app-release-unsigned.apk
